version: "3.9"

services:
  database:
    image: postgres
    container_name: database_crud_node
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local